---
- name: Configure Cisco Nexus 9k Switches
  hosts: switches
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos
    ansible_become: true
    ansible_become_method: enable

    vlans: []

    snmp_contact: "Default Contact"
    snmp_location: "Default Location"
    snmp_communities:
      - name: "public"
        permission: "RO"


    ntp_server: "time.nist.gov"
    syslog_server: "syslog.example.com"
    timezone: "CST"
    timezone_offset: "-6"

  tasks:
    - name: Generate NX-OS configuration
      template:
        src: config.j2
        dest: /tmp/config.cfg

    - name: Apply NX-OS configuration
      cisco.nxos.nxos_config:
        src: /tmp/config.cfg
